import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,loadState,STORAGE_KEY,startIncident,endIncident,startTrip,finishTrip,advanceTime,validateContact,validatePins,validPhone,remaining,clock} from '../dist/model.js';
const contact={id:'c1',name:'Contacto de ejemplo',phone:'+1 202 555 0100',relation:'Familiar ficticio'};
function ready(){const s=initialState();s.contacts.push({...contact});return s;}
test('inicio vacío, recuperación y almacenamiento local inaccesible',()=>{const s=initialState();assert.equal(s.contacts.length,0);assert.equal(s.history.length,0);assert.equal(s.pins,null);assert.equal(s.profile.name,'');assert.ok(loadState(undefined).error);assert.ok(loadState({getItem:()=>'{no json'}).error);assert.equal(loadState({getItem:()=>JSON.stringify(s)}).state.version,1);});
test('SOS cancelado no se completa al vencer y conserva contacto y detalles',()=>{const s=ready();assert.equal(startIncident(s,'SOS',10),true);s.incident.note='Prueba de emergencia';const deadline=s.incident.deadline;const e=endIncident(s,'Cancelada');assert.equal(e.status,'Cancelada');assert.match(e.detail,/Contacto de ejemplo/);assert.match(e.detail,/Prueba de emergencia/);assert.equal(advanceTime(s,deadline+1).length,0);assert.equal(s.history.length,2);});
test('SOS vencido registra una única finalización y no alerta real',()=>{const s=ready();startIncident(s,'SOS',5);assert.equal(startIncident(s,'Drive',5),false);const results=advanceTime(s,s.incident.deadline+1);assert.equal(results[0].kind,'incident');assert.equal(s.incident,null);assert.match(results[0].event.detail,/Ninguna persona/);assert.equal(advanceTime(s,Date.now()+60000).length,0);});
test('Drive y accidente conservan su tipo al cancelar y completar',()=>{for(const type of ['Drive','Accidente']){const s=initialState();startIncident(s,type,15);advanceTime(s,s.incident.deadline);assert.equal(s.history[0].type,type);assert.equal(s.history[0].status,'Simulación completada');}});
test('trayecto exige destino, contacto existente y tiempo válido',()=>{const s=ready();assert.ok(startTrip(s,'',contact.id,15));assert.ok(startTrip(s,'Casa','inexistente',15));assert.ok(startTrip(s,'Casa',contact.id,0));assert.ok(startTrip(s,'Casa',contact.id,1.5));assert.equal(s.trip,null);assert.equal(startTrip(s,'Casa',contact.id,15),null);assert.ok(startTrip(s,'Otra',contact.id,20));});
test('trayecto vence, verifica y escala exactamente una vez',()=>{const s=ready();startTrip(s,'Destino ficticio',contact.id,1);const first=advanceTime(s,s.trip.deadline+1);assert.equal(first[0].kind,'trip-check');assert.equal(s.trip.status,'verifying');assert.equal(advanceTime(s,s.trip.verifyDeadline-1).length,0);assert.equal(advanceTime(s,s.trip.verifyDeadline)[0].kind,'trip-escalated');assert.equal(s.trip.status,'escalated');assert.match(s.history[0].detail,/no recibió ningún mensaje/);assert.equal(advanceTime(s,Date.now()+9999999).length,0);});
test('confirmar llegada elimina verificación pendiente; contacto es instantánea',()=>{const s=ready();startTrip(s,'Casa',contact.id,1);s.contacts=[];assert.equal(s.trip.contact.name,contact.name);advanceTime(s,s.trip.deadline);finishTrip(s,'Llegada confirmada');assert.equal(s.trip,null);assert.equal(s.history[0].status,'Llegada confirmada');assert.equal(advanceTime(s,Date.now()+999999).length,0);});
test('cancelar trayecto detiene sus estados posteriores',()=>{const s=ready();startTrip(s,'Casa',contact.id,1);finishTrip(s,'Cancelado');assert.equal(advanceTime(s,Date.now()+999999).length,0);assert.equal(s.history[0].status,'Cancelado');});
test('Tutor escala sin respuesta y confirmar evita el escalamiento',()=>{const s=initialState();s.tutor={status:'waiting',deadline:Date.now()+20000};advanceTime(s,s.tutor.deadline);assert.equal(s.tutor.status,'escalated');assert.equal(s.history[0].type,'Tutor');assert.equal(advanceTime(s,Date.now()+999999).length,0);s.tutor={status:'confirmed',deadline:null};assert.equal(advanceTime(s,Date.now()+999999).length,0);});
test('persistencia conserva preferencias, perfil, contactos, historial y plazos',()=>{const s=ready();s.profile.name='Perfil de ejemplo';s.drive={active:true,consent:true,transport:'Automóvil',placement:'Bolsillo',seconds:10};startTrip(s,'Casa',contact.id,1);startIncident(s,'Drive',10);const restored=loadState({getItem:key=>{assert.equal(key,STORAGE_KEY);return JSON.stringify(s);}}).state;assert.deepEqual(restored,s);assert.equal(advanceTime(restored,s.incident.deadline)[0].kind,'incident');});
test('validación de contactos: campos, teléfono y duplicados',()=>{const s=ready();assert.equal(validPhone('+1 202 555 0100'),true);assert.equal(validPhone('tel:911'),false);assert.equal(validPhone('123'),false);assert.ok(validateContact(s,{...contact,name:' '}));assert.ok(validateContact(s,{...contact,phone:'123'}));assert.ok(validateContact(s,{...contact,relation:''}));assert.ok(validateContact(s,contact));assert.equal(validateContact(s,contact,contact.id),null);});
test('PINs no se precargan y deben ser diferentes, numéricos y de 4 a 6 dígitos',()=>{assert.equal(initialState().pins,null);assert.ok(validatePins('2222','2222'));assert.ok(validatePins('abcd','5555'));assert.ok(validatePins('123','5555'));assert.equal(validatePins('2580','3579'),null);});
test('temporizador nunca negativo y representación minutos/segundos',()=>{assert.equal(remaining(1000,2000),0);assert.equal(remaining(2001,1000),2);assert.equal(clock(75),'01:15');});
